"""empty message

Revision ID: 64afcc2911c0
Revises: 9dd0e9c9b6ea
Create Date: 2021-10-29 13:13:52.645425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64afcc2911c0'
down_revision = '9dd0e9c9b6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('username', sa.String(length=20), nullable=True))
    op.drop_column('message', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('name', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('message', 'username')
    # ### end Alembic commands ###
