"""20211029 add message model

Revision ID: 9dd0e9c9b6ea
Revises: aca6eed84432
Create Date: 2021-10-29 11:24:52.632930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dd0e9c9b6ea'
down_revision = 'aca6eed84432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('contents', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('productcarslist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productcarslist',
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('productName_toBuy', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('price_toBuy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('message')
    # ### end Alembic commands ###
