"""20211028

Revision ID: aca6eed84432
Revises: 
Create Date: 2021-10-28 15:35:44.175327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aca6eed84432'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productCarsList',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('productName_toBuy', sa.String(length=30), nullable=True),
    sa.Column('price_toBuy', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.drop_table('productcarslist')
    op.drop_table('shop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('productName', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Mount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pid'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('productcarslist',
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('productName_toBuy', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('price_toBuy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('productCarsList')
    # ### end Alembic commands ###
