"""productcar

Revision ID: e58dc4ae694e
Revises: 0fe6106697a0
Create Date: 2021-11-03 11:22:50.012462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e58dc4ae694e'
down_revision = '0fe6106697a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bike')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('StationName', mysql.CHAR(charset='utf8mb4', length=20), nullable=True),
    sa.Column('Available_bike', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
