# Generated by Django 3.2.6 on 2021-12-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=20)),
                ('url', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=200)),
            ],
        ),
    ]
