# Generated by Django 3.2.6 on 2021-12-10 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('comment', models.TextField(max_length=300)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createtime')),
            ],
        ),
    ]
