# Generated by Django 3.2.6 on 2021-12-22 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_models',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='save_date'),
        ),
        migrations.AlterField(
            model_name='users_models',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='update_date'),
        ),
    ]
