# Generated by Django 3.2.6 on 2021-12-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pid',
            new_name='id',
        ),
    ]
