# Generated by Django 3.2.6 on 2021-12-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_rename_pid_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
